language: php
php:
- '7.0'
services:
- docker
before_install:
- sudo apt-get -y update || true
- sudo apt-get -y install cgroup-bin curl
- curl -fsSL -o /tmp/lando-latest.deb http://installer.kalabox.io/lando-latest-dev.deb
- sudo dpkg -i /tmp/lando-latest.deb
- lando version
script:
- lando start -- -v
- lando composer install
- lando composer prepare-for-pantheon
- lando phplint
- lando terminus auth:login --machine-token=$PANTHEON_MACHINE_TOKEN
- lando pull --code=none --database=dev --files=dev --rsync
- cd web
- lando drush cr | grep "rebuild complete."
- cd ..
- lando behat --config=/app/tests/behat-pantheon.yml
- |
  if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    BRANCH=$(echo $TRAVIS_PULL_REQUEST_BRANCH | grep -v '^\(master\|[0-9]\+.x\)$')
    PR_ENV=${BRANCH:+pr-$BRANCH}
    DEFAULT_ENV=$(echo ${PR_ENV:-$TRAVIS_PULL_REQUEST_BRANCH} | tr '[:upper:]' '[:lower:]' | sed 's/[^0-9a-z-]//g' | cut -c -11 | sed 's/-$//')
    if ! lando terminus multidev:list $PANTHEON_SITE_NAME --field id | grep "$DEFAULT_ENV"; then
      lando terminus multidev:create $PANTHEON_SITE_NAME.dev $DEFAULT_ENV
    fi
    lando ssh -c "cd /tmp && git clone -b $DEFAULT_ENV ssh://codeserver.dev.\${PANTHEON_SITE}@codeserver.dev.\${PANTHEON_SITE}.drush.in:2222/~/repository.git pantheon_build"
    lando ssh -u root -c "rm -rf /tmp/pantheon_build/*"
    lando ssh -c "cp -rf /app/ /tmp/pantheon_build/"
    lando ssh -c "git -C /tmp/pantheon_build add -A"
    lando ssh -c "git -C /tmp/pantheon_build commit -m '$TRAVIS_COMMIT_MESSAGE'"
    lando ssh -c "git -C /tmp/pantheon_build push origin $DEFAULT_ENV"
  fi
- lando terminus ssh-key:remove $(ssh-keygen -l -f ~/.lando/keys/pantheon.lando.id_rsa.pub
  | awk -F' ' '{print $2}' | sed 's/://g')
deploy:
  provider: script
  script: scripts/travis/deploy.sh $DEFAULT_ENV
  on:
    branch: master
env:
  global:
    secure: M7Rr/oXcXUQYQm/8n3TOQRoBG+SRYinwJb/o33W4Coigz9suKRcy4EzBmK5/pA8Yw3D74fHJJufDs9U9gMr/uFp5E0OfwpL0n5CENhqWxj0YOMKbOlUd6IjdnDTkiMLN0Hb11N0Ih4k6OG5iQB2V9dLDrD7deGJO5K+hCKBaInhSErO+JzsBix+cYjmuTwC0xoDDa/3WfETpDwE/pwkfrzZOaIxj4jdgs5xvAQLoFjA+p0xuXJOWa5AxH94ekoX4E3KUUurO1mHheWi2re6Eefau/gEmgQutd/jnbJx236vmwdvthvYft93tusy+4DistZ5KgDAzWv1soKU+4n7e6x9/an/yEKL/CGR6IQMOVUFM4zVJQqfL9LUMKEFAYPzsd4XUYDSZ3v+QMkphU6dyPFWdWGZ5z1NcVveASLmdleYz9tYTYOdxW5PqD5agPQlDnuREOe9KaL7wrZvNyMbOa/zK4T7NgD3YHHpkAkWJ69wdftyw1mlKjYqI9hYrXpXF/4uylKUr1vjWk/JG+5l9R3vdeoTCpmcBmM2+4Kt3Tr7p4SzWNwjSPc3YmhPtJjOQ7mBBljdSFzftpZaXhsz0UlGtFYYttcouI4/oyPNxdIZgdu+EUjrP7XapTBYaAutdOD7d13eVxO22OitLqzqbMhviZ+0QHbidaAsLFHkxM5c=
